var HomeObj={setSubmitDialog:function(){$("#submit_dialog").dialog({autoOpen:!1,modal:!0,draggable:!1,resizable:!1,title:"Submit Ticket",minWidth:400,open:function(){$("html,body").css("overflow","hidden")},close:function(){$(this).find("#progressbar").progressbar("value",0);$("#pBar").attr("value",1);$("html,body").css("overflow","auto");$(".finished").html("");$(".finished").hide();$(".waiting").show()}})},setDocumentDropdownBlur:function(){$(document).bind("click",function(){return function(){$(".menuHeader").each(function(){$(this).is(":visible")&&
$(this).hide()})}}())}};
HomeObj.submitTicketData=function(){MainObj.clearWarnings();var a=$("#submit_dialog").dialog("open");a.find("#progressbar").progressbar();var c={};$("#client_data input[type!=button], #client_data textarea").not("#display_deadline").each(function(){c[$(this).attr("id")]=$(this).val()});c.Priority=$("#Priority :selected").val();c.Department=$("#Department :selected").val();$("#equipment_table [id*=Equipment_]").not("#Equipment_DEFAULT").each(function(){c["Equipment["+$(this).attr("id")+"][Make]"]=
$(this).find("#Make").val();c["Equipment["+$(this).attr("id")+"][Model]"]=$(this).find("#Model").val();c["Equipment["+$(this).attr("id")+"][Type]"]=$(this).find("#Type").val();c["Equipment["+$(this).attr("id")+"][Notes]"]=$(this).find("#Notes").val()});$.post("/homeAjax/submitTicketData",c,function(b){if(void 0!=b&&!0==b.success)$("#waiting_message").html("Sending to Kayako Fusion..."),$("#pBar").attr("value",50),$.post("homeAjax/syncTicketWithFusion",{PK_TicketNum:b.TicketID},function(c){$("#pBar").attr("value",
100);if(c.success){$("div.waiting").hide();var b=$("div.finished");b.css("text-align","center");b.append(HomeObj.fetchBarcode(c.TicketID+""));b.append("<p>The request is complete.<p>");b.show()}else a.dialog("close"),MainObj.jAlert("An Error has occurred.")},"json");else{for(var c in b.Errors)MainObj.displayWarning(b.Errors[c]);a.dialog("close");document.location="#"}},"json")};
HomeObj.toggleEquipmentCollapse=function(a){tr=$(a).closest("tr[id^=Equipment_]");a=tr.find("table.equipment");a.is(":visible")?(tr.find("span.expansion").css("background-position","0 -33px"),a.hide()):(tr.find("span.expansion").css("background-position","0 5px"),a.show(),tr.find("input:first").focus(),$.scrollTo(a))};
HomeObj.setEquipmentTitle=function(a){var a=$(a).closest("tr[id^=Equipment_]"),c=a.find(".equipment_banner span"),b=a.find("input[id=Model]").val(),d=a.find("input[id=Make]").val();""==d&&""==b?(c.html("["+a.attr("id")+"]"),c.addClass("unchanged")):(c.html(d+" "+b),c.removeClass("unchanged"))};
HomeObj.addEquipment=function(){var a=$("#equipment_table"),c=$("#Equipment_DEFAULT").detach(),b=$("#equipment_table > tbody > tr").length+1,d=c.clone();d.attr("id","Equipment_"+b);d.find(".equipment_banner span").html("[Equipment_"+b+"]");a.append(d);a.append(c);d.show();$.scrollTo(d);d.find("input:first").focus()};
HomeObj.removeEquipment=function(a){$(a).closest(".equipment_row").remove();var a=$(".equipment_row").not("#Equipment_DEFAULT"),c=a.length;a.sort(function(a,b){return parseInt($(a).attr("id").match(/\d+/))-parseInt($(b).attr("id").match(/\d+/))});for(var b=1;b<=c;b++)$(a[b-1]).attr("id","equipment_"+b),$(a[b-1]).find(".equipment_banner span").hasClass("unchanged")&&$(a[b-1]).find(".equipment_banner span").html("[Equipment_"+b+"]")};
HomeObj.fetchBarcode=function(a){if(""==a||void 0==a)console.log("Error: No text specified for the barcode");else if(void 0==container)console.log("Error: No container specified.");else return a=a.replace(/[^a-zA-Z0-9- ]/g,""),$("<img />").attr("src","/homeAjax/createBarcode/"+a)};